// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijnqwgywaduupvmjnlfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbnF3Z3l3YWR1dXB2bWpubGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDM3OTIsImV4cCI6MjA3MjYxOTc5Mn0.M8Np7fWNq5nHptE14_59cBRg1Jc7t6SBmeHKyfM5n3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});